Repository PJT-16-3/KB_BE, pull requests merged in 2025-07, with the labels that each got.

#27 feat: 가점 계산기 기능 구현
  src/main/java/org/scoula/controller/AccountController.java
  src/main/java/org/scoula/controller/GaScoreController.java
  src/main/java/org/scoula/dto/GaScoreDTO.java
  src/main/java/org/scoula/mapper/AccountMapper.java
  src/main/java/org/scoula/mapper/GaScoreMapper.java
  src/main/java/org/scoula/service/CodefApiService.java
  src/main/java/org/scoula/service/GaScoreService.java
  src/main/resources/application.properties
  src/main/resources/org/scoula/mapper/AccountMapper.xml
  src/main/resources/org/scoula/mapper/GaScoreMapper.xml
Labels: ✨Feature, 🛠️Refactor

#55 Feat: 사용자 선호조건 등록
  .gitignore
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/description.html
  .idea/gradle.xml
  .idea/misc.xml
  .idea/project-template.xml
  .idea/template-meta.xml
  .idea/vcs.xml
  README.md
  build.gradle
  src/main/java/org/scoula/config/MailConfig.java
  src/main/java/org/scoula/config/RootConfig.java
  src/main/java/org/scoula/config/ServletConfig.java
  src/main/java/org/scoula/config/WebConfig.java
  src/main/java/org/scoula/controller/AccountController.java
  src/main/java/org/scoula/controller/AuthController.java
  src/main/java/org/scoula/controller/GaScoreController.java
  src/main/java/org/scoula/controller/KakaoLoginController.java
  src/main/java/org/scoula/controller/SecurityController.java
  src/main/java/org/scoula/controller/UserSelectedController.java
  src/main/java/org/scoula/domain/User.java
  src/main/java/org/scoula/dto/AccountConnectDTO.java
  src/main/java/org/scoula/dto/ChungyakAccountDTO.java
  src/main/java/org/scoula/dto/GaScoreDTO.java
  src/main/java/org/scoula/dto/HomePriceDTO.java
  src/main/java/org/scoula/dto/HomeSizeDTO.java
  src/main/java/org/scoula/dto/HomeTypeDTO.java
  src/main/java/org/scoula/dto/RegionDTO.java
  src/main/java/org/scoula/dto/UserSelectedDTO.java
  src/main/java/org/scoula/dto/oauth/KakaoUserInfoDto.java
  src/main/java/org/scoula/mapper/AccountMapper.java
  src/main/java/org/scoula/mapper/GaScoreMapper.java
  src/main/java/org/scoula/mapper/SelectedMapper.java
  src/main/java/org/scoula/mapper/UserMapper.java
  src/main/java/org/scoula/security/config/SecurityConfig.java
  src/main/java/org/scoula/security/dto/AuthDTO.java
  src/main/java/org/scoula/security/dto/MemberDTO.java
  src/main/java/org/scoula/security/dto/UserInfoDTO.java
  src/main/java/org/scoula/security/util/JwtProcessor.java
  src/main/java/org/scoula/service/CodefApiService.java
  src/main/java/org/scoula/service/EmailService.java
  src/main/java/org/scoula/service/EmailVerification.java
  src/main/java/org/scoula/service/GaScoreService.java
  src/main/java/org/scoula/service/UserSelectedService.java
  src/main/java/org/scoula/service/UserService.java
  src/main/java/org/scoula/service/oauth/KakaoOauthService.java
  src/main/java/org/scoula/util/RsaEncryptionUtil.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/mybatis-config.xml
  src/main/resources/org/scoula/mapper/AccountMapper.xml
  src/main/resources/org/scoula/mapper/GaScoreMapper.xml
  src/main/resources/org/scoula/mapper/SelectedMapper.xml
  src/main/resources/org/scoula/mapper/UserMapper.xml
  src/main/resources/org/scoula/security/account/mapper/UserDetailsMapper.xml
  src/main/webapp/WEB-INF/views/result.jsp
  src/test/java/org/scoula/security/account/mapper/UserDetailsMapperTest.java
  src/test/java/org/scoula/security/util/JwtProcessorTest.java
  src/test/java/org/scoula/service/EmailServiceTest.java
Labels: ✨Feature

#57 feat: 사용자 선호조건 저장
  .gitignore
  .idea/.gitignore
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  .idea/description.html
  .idea/gradle.xml
  .idea/misc.xml
  .idea/project-template.xml
  .idea/template-meta.xml
  .idea/vcs.xml
  README.md
  build.gradle
  src/main/java/org/scoula/config/MailConfig.java
  src/main/java/org/scoula/config/RootConfig.java
  src/main/java/org/scoula/config/ServletConfig.java
  src/main/java/org/scoula/config/WebConfig.java
  src/main/java/org/scoula/controller/AccountController.java
  src/main/java/org/scoula/controller/AuthController.java
  src/main/java/org/scoula/controller/GaScoreController.java
  src/main/java/org/scoula/controller/KakaoLoginController.java
  src/main/java/org/scoula/controller/SecurityController.java
  src/main/java/org/scoula/controller/SignUpController.java
  src/main/java/org/scoula/controller/UserSelectedController.java
  src/main/java/org/scoula/domain/User.java
  src/main/java/org/scoula/dto/HomePriceDTO.java
  src/main/java/org/scoula/dto/HomeSizeDTO.java
  src/main/java/org/scoula/dto/HomeTypeDTO.java
  src/main/java/org/scoula/dto/RegionDTO.java
  src/main/java/org/scoula/dto/UserSelectedDTO.java
  src/main/java/org/scoula/dto/oauth/KakaoUserInfoDto.java
  src/main/java/org/scoula/mapper/SelectedMapper.java
  src/main/java/org/scoula/mapper/UserMapper.java
  src/main/java/org/scoula/security/config/SecurityConfig.java
  src/main/java/org/scoula/security/dto/AuthDTO.java
  src/main/java/org/scoula/security/dto/MemberDTO.java
  src/main/java/org/scoula/security/dto/UserDTO.java
  src/main/java/org/scoula/security/dto/UserInfoDTO.java
  src/main/java/org/scoula/security/util/JwtProcessor.java
  src/main/java/org/scoula/service/CodefApiService.java
  src/main/java/org/scoula/service/EmailService.java
  src/main/java/org/scoula/service/EmailVerificationService.java
  src/main/java/org/scoula/service/UserSelectedService.java
  src/main/java/org/scoula/service/UserService.java
  src/main/java/org/scoula/service/oauth/KakaoOauthService.java
  src/main/java/org/scoula/util/RsaEncryptionUtil.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/mybatis-config.xml
  src/main/resources/org/scoula/mapper/SelectedMapper.xml
  src/main/resources/org/scoula/mapper/UserMapper.xml
  src/main/resources/org/scoula/security/account/mapper/UserDetailsMapper.xml
  src/test/java/org/scoula/security/account/mapper/UserDetailsMapperTest.java
  src/test/java/org/scoula/security/util/JwtProcessorTest.java
  src/test/java/org/scoula/service/EmailServiceTest.java
  src/test/java/org/scoula/service/EmailVerificationServiceTest.java
Labels: ✨Feature

#68 refactor: gitignore 수정
  .gitignore
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  src/main/java/org/scoula/dto/UserSelectedDTO.java
Labels: 🛠️Refactor

#70 refactor: JSON 요청 및 응답 양식 수정
  .idea/.gitignore
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  settings.gradle
  src/main/java/org/scoula/controller/AccountController.java
  src/main/java/org/scoula/controller/GaScoreController.java
  src/main/java/org/scoula/controller/UserSelectedController.java
  src/main/java/org/scoula/dto/AccountConnectDTO.java
  src/main/java/org/scoula/dto/ChungyakAccountDTO.java
  src/main/java/org/scoula/dto/GaScoreDTO.java
  src/main/java/org/scoula/dto/HomePriceDTO.java
  src/main/java/org/scoula/dto/HomeSizeDTO.java
  src/main/java/org/scoula/dto/HomeTypeDTO.java
  src/main/java/org/scoula/dto/RegionDTO.java
  src/main/java/org/scoula/dto/UserSelectedDTO.java
  src/main/java/org/scoula/exception/GlobalExceptionHandler.java
  src/main/java/org/scoula/exception/NoAccountException.java
  src/main/java/org/scoula/service/CodefApiService.java
  src/main/java/org/scoula/service/UserSelectedService.java
  src/test/java/org/scoula/security/account/mapper/UserDetailsMapperTest.java
Labels: 🛠️Refactor

#101 feat: KakaoLogin 기능 구현 완료(추가정보 포함)
  .idea/artifacts/Gradle___org_scoula___KB_BE_1_0_SNAPSHOT_war.xml
  .idea/artifacts/Gradle___org_scoula___KB_BE_1_0_SNAPSHOT_war__exploded_.xml
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  src/main/java/org/scoula/controller/KakaoLoginController.java
  src/main/java/org/scoula/controller/UserFavoriteController.java
  src/main/java/org/scoula/dto/FavoriteRequestDTO.java
  src/main/java/org/scoula/dto/UserFavoriteDTO.java
  src/main/java/org/scoula/dto/oauth/KakaoUserInfoDto.java
  src/main/java/org/scoula/mapper/UserFavoriteMapper.java
  src/main/java/org/scoula/security/dto/MemberDTO.java
  src/main/java/org/scoula/service/UserFavoriteService.java
  src/main/java/org/scoula/service/oauth/KakaoOauthService.java
  src/main/resources/org/scoula/mapper/UserFavoriteMapper.xml
  src/test/java/org/scoula/security/account/mapper/UserDetailsMapperTest.java
  src/test/java/org/scoula/service/UserFavoriteServiceTest.java
  src/test/java/org/scoula/service/oauth/KakaoOauthServiceTest.java
Labels: ✨Feature, 🌐Server, 🔒Security

#133 feat: 지도 인프라 정보 호출 및 저장
  .idea/dataSources.xml
  src/main/java/org/scoula/controller/UserSelectedController.java
  src/main/java/org/scoula/dto/AptDTO.java
  src/main/java/org/scoula/dto/PlaceDTO.java
  src/main/java/org/scoula/mapper/AptMapper.java
  src/main/java/org/scoula/mapper/PlaceMapper.java
  src/main/java/org/scoula/service/KakaoMapInfraService.java
  src/main/resources/org/scoula/mapper/AptMapper.xml
  src/main/resources/org/scoula/mapper/PlaceMapper.xml
  src/test/java/org/scoula/service/KakaoMapInfraServiceTest.java
Labels: ✨Feature, 🌐Server

#138 feat: 계좌 연결 해제 및 DB 삭제
  .idea/artifacts/Gradle___org_scoula___KB_BE_1_0_SNAPSHOT_war__exploded_.xml
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  src/main/java/org/scoula/controller/AccountController.java
  src/main/java/org/scoula/mapper/AccountMapper.java
  src/main/java/org/scoula/service/CodefApiService.java
  src/main/resources/org/scoula/mapper/AccountMapper.xml
Labels: ✨Feature

#139 feat: 계좌 연결 해제 및 DB 삭제
  .idea/artifacts/Gradle___org_scoula___KB_BE_1_0_SNAPSHOT_war__exploded_.xml
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  src/main/java/org/scoula/controller/AccountController.java
  src/main/java/org/scoula/dto/AptDTO.java
  src/main/java/org/scoula/dto/OfficetelDTO.java
  src/main/java/org/scoula/dto/PlaceDTO.java
  src/main/java/org/scoula/mapper/AccountMapper.java
  src/main/java/org/scoula/mapper/AptMapper.java
  src/main/java/org/scoula/mapper/PlaceMapper.java
  src/main/java/org/scoula/service/CodefApiService.java
  src/main/java/org/scoula/service/KakaoMapInfraService.java
  src/main/resources/org/scoula/mapper/AccountMapper.xml
  src/main/resources/org/scoula/mapper/AptMapper.xml
  src/main/resources/org/scoula/mapper/PlaceMapper.xml
  src/test/java/org/scoula/service/KakaoMapInfraServiceTest.java
Labels: ✨Feature
